spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  application:
    name: team5
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        auto_quote_keyword: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  jwt:
    secret: ${JWT_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
app:
  api:
    url: https://dsrkzpzrzxqkarjw.tunnel-pt.elice.io