spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  application:
    name: team5
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        auto_quote_keyword: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'