spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  application:
    name: team5
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        auto_quote_keyword: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  jwt:
    secret: dc5e9dd80f65e4ac4f67b718c01d50f02cf84b697d5ba6cfe2f4dddf2ecda8ff

  config:
    import:
      - s3bucket-sample.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true